squash allchanges
puzzle/okr pull request #1017
Opened 2024-09-30 10:20 UTC by kcinay055679

2024-10-03 08:02 UTC, pizzi-cato requested changes

2024-10-03 08:02 UTC, pizzi-cato commented on backend/src/test/java/ch/puzzle/okr/util/quarter/generate/h2/QuarterFunctionTest.java
> +        String expectedNext = "(3, GJ 24/25-Q3, 2025-01-01, 2025-03-31)";
dito

2024-10-03 11:43 UTC, pizzi-cato reviewed
- merge problems are solved in backend
- try to fix e2e tests

2024-10-03 11:51 UTC, pizzi-cato commented
merge problems are solved in backend
try to fix e2e tests

2024-10-03 12:38 UTC, pizzi-cato approved these changes

2024-10-03 12:40 UTC, pizzi-cato requested changes
- e2e tests fixed
- application runs for pitc (data available, team administration looks good for me)
- application fails while authenticating acme (loop for ever, even we do not use Shibboleth :-) )

2024-10-03 13:02 UTC, clean-coder commented
Ein paar Infos zu **Einloggen mit dem Browser als acme**
- einloggen (authentication) funktioniert mit dem aktuellen Stand im Branch nicht mehr
- Ursache ist, dass die ` "angular-oauth2-oidc": "^17.0.0"` Library ersetzt wurde durch `"angular-auth-oidc-client": "^18.0.1"` . Man kann die git History vom `package.json` File anschauen und sieht dann, das am `09.09.2024` beim fixen eine Bugs auf die andere Library umgestellt wurde.
- Wenn man wieder auf die alte Library umstellt (und den Code in den entsprechenden Klassen und Tests anpasst), kann auch wieder einloggen. Dies wäre sicherlich ein gangbarer Weg fürs Merging in den `master`. Mann dann in einem spätere Schritt entscheiden, ob man längerfristig weitergehen will (mit der alten oder neuen Library und den möglichen Konsequenzen).

2024-10-04 04:20 UTC, clean-coder commented
Tip zum  **Einloggen mit dem Browser als acme**
Betroffen sind aus meiner Sicht folgende 18 Files. Ich habe diese mal als "POC" auf den alten Stand zurückgesetzt, und dann hat es mit `acme` wieder gekappt.

![image](https://github.com/user-attachments/assets/f6115b7c-41fc-4cbd-9b04-e973505b1239)

2024-10-11 14:31 UTC, peggimann requested changes
Also Login does not work properly atm

2024-10-14 11:00 UTC, kcinay055679 commented on frontend/cypress/e2e/tab.cy.ts
> +    it.skip('Duplicate objective with tab', () => {
https://github.com/orgs/puzzle/projects/3/views/1?pane=issue&itemId=83284114&issue=puzzle%7Cokr%7C1024

2024-10-14 11:27 UTC, peggimann approved these changes

2024-10-14 11:28 UTC, merged