Feature/623 header mobile
puzzle/okr pull request #1074
Opened 2024-10-22 13:52 UTC by nevio18324

2024-11-07 14:17 UTC, MasterEvarior requested changes
Sieht schon sehr gut aus! :tada: 
Funkioniert (fast) problemlos und sieht aus wie von UX vorgegeben. 
Mir sind noch einige kleinere Sachen im Code aufgefallen +das:

Momentan ist der mehr/weniger-Button immer vorhanden. Wenn es allerdings nicht mehr Teams gibt alls diejeningen, welche schon angezeigt werden, dann passiert einfach nichts. Könnte man den Button stattdessen nicht anzeigen?
[Screencast_20241107_150908.webm](https://github.com/user-attachments/assets/8c292f49-12f7-4c8d-89c9-71d0461983d6)

2024-11-07 14:17 UTC, MasterEvarior commented on frontend/src/app/components/team-filter/team-filter.component.ts
> +    return teamName ?? 'no team name';
Falls es tatsächlich vorkommen kann, das ein Team keinen Namen hat, dann müsste die Message hier auch noch i18n-ed werden.

2024-11-08 14:59 UTC, peggimann requested changes

2024-11-08 14:59 UTC, peggimann commented on frontend/cypress/e2e/tab.cy.ts
> +    it.only('Duplicate objective with tab', () => {
Must be removed yes.

2024-11-08 14:59 UTC, peggimann commented on frontend/cypress/e2e/tab.cy.ts
> -      cy.focused().contains('GJ');
why did dublicate Objective test change in Header Ticket?

2024-11-08 14:59 UTC, peggimann commented on frontend/src/app/components/objective/objective.component.spec.js
Muss zwingend ts sein, refactor

2024-11-08 14:59 UTC, peggimann commented on frontend/src/app/components/team-filter/team-filter.component.html
> +  <button (click)="toggleAll()" class="icon-button team-button focus-outline d-none d-sm-block" id="diddy">
an id should be descriptive. This is bad practice...

2024-11-08 14:59 UTC, peggimann commented on frontend/src/app/components/team-filter/team-filter.component.ts
> +    let teamName = this.teams$.getValue().find((team) => team.id === id)?.name;
maybe solve this with css, wordbreak and elipsis

2024-11-20 12:57 UTC, MasterEvarior requested changes

2024-11-20 12:57 UTC, MasterEvarior commented on frontend/src/app/components/team-filter/team-filter.component.ts
> +  showMoreTeams = true;
```suggestion
  showMoreTeams: boolean = true;
```
Nitpick

2024-11-20 12:57 UTC, MasterEvarior commented on frontend/src/app/components/team-filter/team-filter.component.ts
If possible a test for the `isMobile` would be nice. If it is too inpractical, leave it be.

2024-11-22 08:29 UTC, peggimann requested changes

2024-11-22 08:29 UTC, peggimann commented on .run/OkrApplication-E2E.run.xml
> -    <option name="ALTERNATIVE_JRE_PATH_ENABLED" value="true" />
readd this line

2024-11-22 09:04 UTC, peggimann approved these changes

2024-11-22 09:04 UTC, merged