Feature/354/keyresult delete
puzzle/okr pull request #113
Opened 2023-01-09 15:00 UTC by njaeggi

2023-01-10 12:49 UTC, tuxmatta requested changes

2023-01-10 12:49 UTC, tuxmatta commented on frontend/src/app/shared/dialog/confirm-dialog/confirm-dialog.component.ts
> +    this.dialogRef.close(false);
Könnte man auch testen.

2023-01-10 12:49 UTC, tuxmatta commented on frontend/src/app/shared/dialog/confirm-dialog/confirm-dialog.component.ts
> +    this.dialogRef.close(true);
Könnte man auch testen.

2023-01-16 14:54 UTC, tuxmatta requested changes

2023-01-16 14:54 UTC, tuxmatta commented on frontend/src/app/shared/spinner/spinner/spinner.component.ts
> +import { BehaviorSubject } from 'rxjs';
Import überflüssig

2023-01-16 14:54 UTC, tuxmatta commented on frontend/src/app/shared/spinner/spinner/spinner.component.ts
> +  @Input() visibility!: boolean;
Am Besten die Input-Variable direkt mit `false` initialisieren.

2023-01-16 14:54 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-row/key-result-row.component.ts
> +              this.toastr.error(
Es wäre gut, wenn man den Dialog auch im Fehlerfall schliesst.

2023-01-16 14:54 UTC, tuxmatta commented on frontend/src/app/shared/dialog/confirm-dialog/confirm-dialog.component.ts
> +  ngOnInit(): void {}
ngOnInit() + OnInit löschen

2023-01-17 10:30 UTC, MarcEgliP commented on backend/src/main/java/ch/puzzle/okr/service/KeyResultService.java
> +    public void deleteKeyResultById(Long id) {
@Transactional wurde hinzugefügt

2023-01-17 10:31 UTC, MarcEgliP commented on frontend/src/app/shared/spinner/spinner/spinner.component.ts
> +import { BehaviorSubject } from 'rxjs';
Import wurde entfernt

2023-01-17 10:31 UTC, MarcEgliP commented on frontend/src/app/shared/spinner/spinner/spinner.component.ts
> +  @Input() visibility!: boolean;
Input-Variable wurde mit false initialisiert

2023-01-17 10:33 UTC, MarcEgliP commented on frontend/src/app/keyresult/key-result-row/key-result-row.component.ts
> +              this.toastr.error(
Dialog wird nun auch bei Fehler noch vor der Toastrmeldung geschlossen.

2023-01-17 10:34 UTC, MarcEgliP commented on frontend/src/app/shared/dialog/confirm-dialog/confirm-dialog.component.ts
> +  ngOnInit(): void {}
ngOnInit() plus das Interface OnInit wurde entfernt

2023-01-17 11:47 UTC, tuxmatta approved these changes

2023-01-17 11:47 UTC, merged