make topbar background color of staging violet to visualize its stagi…
puzzle/okr pull request #1208
Opened 2024-11-25 13:38 UTC by nevio18324

…ng environment

2024-12-02 14:21 UTC, RandomTannenbaum commented on backend/src/main/resources/application-demo.properties
> +okr.tenants.pitc.clientcustomization.customstyles.okr-add-objective-text-color=#ffffff
Use mid-grey (see figma)

2024-12-02 14:23 UTC, RandomTannenbaum commented on backend/src/main/resources/application-demo.properties
> +okr.tenants.pitc.clientcustomization.customstyles.okr-add-objective-outline-color=#ffffff
Check outline color

2024-12-02 14:36 UTC, RandomTannenbaum approved these changes

2024-12-02 14:36 UTC, RandomTannenbaum commented on frontend/src/app/components/team/team.component.ts
> +  protected addIconSrc: Observable<string> = this.configService.config$.pipe(
Maybe rewrite to using behaviorsubject. For example see overview.component.ts

2024-12-02 14:36 UTC, RandomTannenbaum commented on frontend/src/style/styles.scss
>  .bg-grey {
Check css class naming

2024-12-05 09:06 UTC, MasterEvarior requested changes
Almost there :+1:

2024-12-05 09:06 UTC, MasterEvarior commented on frontend/src/app/components/team/team.component.ts
> +      this.addIconSrc.next(config.customStyles['okr-add-objective-icon'] ?? '/assets/icons/new-icon.svg');
```suggestion
      this.addIconSrc.next(config.customStyles['okr-add-objective-icon']);
```
I think this  is redundant, as the `BehaviorSubject` already has the same default value :thinking: 
I'd rather have a check if the `customStyles[...]` value is `null` and only changing it if it isn't.

2024-12-05 09:06 UTC, MasterEvarior commented on frontend/src/app/components/team/team.component.ts
Maybe also a 1-2 simple unit tests:
- one to check that the correct icon is set
- one the check that the default is applied if nothing is set

2024-12-05 14:12 UTC, MasterEvarior commented on frontend/src/app/components/team/team.component.spec.ts
> +  it('should display right add objective icon', () => {
```suggestion
  it('should display correct add objective icon', () => {
```
Nitpick

2024-12-05 14:58 UTC, MasterEvarior requested changes

2024-12-05 14:58 UTC, MasterEvarior commented on frontend/src/app/components/team/team.component.html
> +          src="{{ (addIconSrc | async) ?? '/assets/icons/new-icon.svg' }}"
```suggestion
          src="{{ (addIconSrc | async)  }}"
```
Remove from here ...

2024-12-05 14:58 UTC, MasterEvarior commented on frontend/src/app/components/team/team.component.ts
> +    });
```suggestion
    this.configService.config$.subscribe((config: ClientConfig) => {
      if(config.customStyles['okr-add-objective-icon']){
         this.addIconSrc.next(config.customStyles['okr-add-objective-icon']);
      }
    });
```
... and move it down here.

This has the benefit that there is only a single place where the fallback is set.

2024-12-11 08:22 UTC, peggimann requested changes

2024-12-11 08:22 UTC, peggimann commented on backend/src/main/resources/application-demo.properties
> +okr.tenants.pitc.clientcustomization.customstyles.okr-overview-background-color=linear-gradient(0deg, #1E5A96, #1E5A96),linear-gradient(180deg, rgba(27, 45, 83, 0.6) 0%, rgba(30, 90, 150, 0.6) 30.84%
somehow the gradient is not applied

2024-12-11 08:22 UTC, peggimann commented on frontend/src/app/components/team/team.component.ts
> +    this.configService.config$.subscribe((config: ClientConfig) => {
this subscribe poses a potential memory leak because it is never properly destroyed

2024-12-12 14:22 UTC, ManuelMoeri requested changes
Make sure to resolve the conversations from before aswell

2024-12-12 14:22 UTC, ManuelMoeri commented on frontend/src/app/components/team/team.component.html
> -<div *ngIf="overviewEntity as OVEntity" class="bg-grey justify-content-between pt-3">
Why was this removed? :thinking:

2024-12-12 14:34 UTC, ManuelMoeri approved these changes
LGTM.

2024-12-12 14:35 UTC, nevio18324 commented on backend/src/main/resources/application-demo.properties
> +okr.tenants.pitc.clientcustomization.helpSiteUrl=https://wiki.puzzle.ch/Puzzle/OKRs
yes

2024-12-13 06:36 UTC, MasterEvarior approved these changes
Looks good to me on demo and staging :+1:

2024-12-13 06:40 UTC, merged