Feature 275 keyresults from objectives
puzzle/okr pull request #15
Opened 2022-11-04 12:21 UTC by njaeggi

2022-11-04 12:22 UTC, njaeggi commented
I left the KeyResultService in for later implementations like getAllKeyResults etc.

2022-11-04 13:02 UTC, tuxmatta reviewed
Sieht gut aus.

2022-11-05 07:26 UTC, tuxmatta requested changes
Es hat viele überflüssige Imports, aber auch ein fehlender Tests und die SwaggerUI Doku ist noch nicht ok.

2022-11-05 07:26 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/service/KeyResultService.java
> +public class KeyResultService {
Diese Klasse wird nicht benötigt. Bitte löschen. So verhindert man MergeKonflikte, wenn ein anderer Branch dieselbe Klasse auch implementiert.

2022-11-05 07:26 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/service/ObjectiveService.java
>  import org.springframework.beans.factory.annotation.Autowired;
Dieser Import wird nicht verwendet.

2022-11-05 07:26 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/service/ObjectiveServiceTest.java
> +import org.springframework.web.server.ResponseStatusException;
Dieser Import wird nicht verwendet.

2022-11-05 07:26 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/service/ObjectiveServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertThrows;
Dieser Import wird nicht verwendet.

2022-11-05 07:26 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/service/ObjectiveServiceTest.java
> +    }
Es fehlt noch der Test, wenn getAllKeyResultsByObjective(objectiveId) kein Objective mit dieser ID findet.

2022-11-05 07:26 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/service/ObjectiveServiceTest.java
> +        Mockito.when(objectiveRepository.findById(1L)).thenReturn(Optional.ofNullable(objective));
Verwende statt `Optional.ofNullable(objective)` folgendes `Optional.of(objective)`. Ich werde am Montag erklären, weshalb.

2022-11-05 07:26 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/controller/ObjectiveController.java
> +    @ApiResponses(value = {
Dokumentation noch nicht korrekt. Hast du die Doku im SwaggerUI angesehen?

2022-11-07 07:34 UTC, peggimann approved these changes
Requested changes are implemented

2022-11-07 07:35 UTC, merged