Feature/265 create team
puzzle/okr pull request #16
Opened 2022-11-04 14:18 UTC by lkleisa

2022-11-05 09:39 UTC, tuxmatta requested changes

2022-11-05 09:39 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/controller/TeamControllerIT.java
> +    void shouldReturnResponseStatusExceptionWhenCreatingTeamEmptyName() throws Exception {
Grundsätzlich genügt in diesem Context 1 Test mit einer Exception. Wir prüfen hier, dass bei auftretender Exception die Information der Exception auch ausgegeben wird. Aktuall leider nur der Status. Ob die richtige Exception geworfen wird, wird der TeamServiceTest überprüfen.
Somit diese Testmethode löschen.

2022-11-05 09:39 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +    void shouldSetNameWhenCreatingTeam() {
Der Testmethoden Name ist unschön. Es wird ja auch die ID generiert und gesetzt. Vorschlag: shouldSaveANewTeam()

2022-11-05 09:39 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +        assertEquals(exception.getMessage(), "400 BAD_REQUEST \"Not allowed to give an id\"");
Bitte in der ganzen Klass anpassen:
1. bei den assertEquals wird zuerste der `Erwartete Wert` und anschliessend der `AktuellZurückgelieferte Wert` angegeben.
2. statt  `exception.getMessage()` wäre schöner `assertEquals("Not allowed to give an id", exception.getReason());`

2022-11-05 09:39 UTC, tuxmatta commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +    void shouldNotCreateTeamWithEmptyName() {
Hier sollte nicht nur ein `""` getestet werden, sondern auch Namen mit Spaces, Tab. du kannst zum Beipiel Parameterisierte Tests verwenden:
https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests

2022-11-05 09:39 UTC, tuxmatta commented on backend/pom.xml
> +        <dependency>
Diese Dependencies benötigt es nicht. Du verwendest diese Annotations in deinem Code nicht. Bitte löschen.

2022-11-07 07:08 UTC, lkleisa commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +    void shouldNotCreateTeamWithEmptyName() {
Danke für den Input, sehr nützlich!

2022-11-07 08:06 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +        Team team = Team.Builder.builder().withName("TestTeam").build();
may be TeamDto instead of Team

2022-11-07 08:06 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +        Team team = Team.Builder.builder().withId(2L).withName("TestTeam").build();
may be TeamDto instead of Team

2022-11-07 08:06 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +        Team team = Team.Builder.builder().withId(null).withName("TestTeam").build();
may be TeamDto instead of Team

2022-11-07 08:06 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +        Team team = Team.Builder.builder().build();
may be TeamDto instead of Team

2022-11-07 08:06 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/TeamServiceTest.java
> +        Team team = Team.Builder.builder().withName(passedName).build();
may be TeamDto instead of Team

2022-11-07 10:03 UTC, peggimann approved these changes

2022-11-07 10:04 UTC, merged