Add label for unit when editing keyresult and adjust tests
puzzle/okr pull request #167
Opened 2023-01-23 14:10 UTC by lkleisa

2023-01-23 16:33 UTC, tuxmatta requested changes

2023-01-23 16:33 UTC, tuxmatta commented on frontend/src/app/keyresult/keyresult-form/keyresult-form.component.spec.ts
> +    test('should be possible to set Key Result unit in mat select', async () => {
Es wäre schöne, wenn man bei `create=true` überprüft, ob man die Einheit auswählen kann und beim `false` die Drop Down fehlt.

2023-01-25 08:32 UTC, lkleisa commented on frontend/src/app/keyresult/keyresult-form/keyresult-form.component.spec.ts
> +    test('should be possible to set Key Result unit in mat select', async () => {
Habe ich hinzugefügt

2023-01-25 09:13 UTC, tuxmatta submitted a review, later dismissed

2023-01-25 09:49 UTC, tuxmatta approved these changes

2023-01-25 09:50 UTC, merged