Feature/158 right date measure
puzzle/okr pull request #172
Opened 2023-01-24 09:19 UTC by kcinay055679

2023-01-25 08:11 UTC, tuxmatta requested changes
Backend.iml !!!!!!!

2023-01-25 08:11 UTC, tuxmatta commented on backend/backend.iml
> +  <component name="NewModuleRootManager">
Ohne Worte!

2023-01-25 12:47 UTC, kcinay055679 commented on backend/backend.iml
> +  <component name="NewModuleRootManager">
Ebenfalls!

2023-01-26 08:05 UTC, tuxmatta approved these changes
Es hat noch Unstimmigkeiten. Da wir die Funktionalität benötigen, wurde dieser PullRequest schon gemerged. 
Die Unstimmigkeiten sind in der Story https://github.com/puzzle/okr/issues/176 erfasst.

2023-01-26 08:11 UTC, tuxmatta approved these changes

2023-01-26 08:12 UTC, merged