Bug/211: Invalid measure form when creating new measure and current date is not in quarter
puzzle/okr pull request #221
Opened 2023-02-01 12:42 UTC by lkleisa

2023-02-01 14:00 UTC, tuxmatta requested changes

2023-02-01 14:00 UTC, tuxmatta commented on frontend/src/app/shared/components/shared/measure-form/measure-form.component.ts
> +          measureDate: this.create ? startEndDate.endDate : measure.measureDate,
Das stimmt nicht mit dem Bug überein:
**SOLL**
Wenn der aktuelle Tag ausserhalb des aktuellen Quartals liegt, so soll der letzte gültige Tag des Quartals verwendet werden.

2023-02-01 14:30 UTC, lkleisa commented on frontend/src/app/shared/components/shared/measure-form/measure-form.component.ts
> +          measureDate: this.create ? startEndDate.endDate : measure.measureDate,
Habe es gelöst

2023-02-01 15:03 UTC, tuxmatta requested changes

2023-02-01 15:03 UTC, tuxmatta commented on frontend/src/app/shared/components/shared/measure-form/measure-form.component.ts
> +  returnQuarterEndDateDatOrCurrentDate(endDate: Date, measureDate: Date) {
returnQuarterEnd**DateDat**OrCurrentDate ??

2023-02-01 15:03 UTC, tuxmatta commented on frontend/src/app/shared/components/shared/measure-form/measure-form.componentCreate.spec.ts
> +  describe('Create new Measure not in the quarter', () => {
Muss man da wirklich ein neues describle einführen? Ist viel Code für ein Test. Es genügt doch die Anfangswerte für diesen Test im Test anzupassen.

2023-02-02 14:19 UTC, tuxmatta approved these changes

2023-02-02 14:19 UTC, merged