implement example-dialog with all necessary html elements to test
puzzle/okr pull request #347
Opened 2023-08-10 07:52 UTC by MarcEgliP

2023-08-10 11:45 UTC, kcinay055679 commented on frontend/src/app/release-1/shared/dialog/example-dialog/example-dialog.component.html
> +        *ngIf="
Simplify as discussed

2023-08-10 11:46 UTC, kcinay055679 commented on frontend/src/app/release-1/shared/dialog/example-dialog/example-dialog.component.html
> +      <mat-radio-button value="other">Other</mat-radio-button>
Change to Mental disability

2023-08-11 10:06 UTC, kcinay055679 requested changes

2023-08-11 10:06 UTC, kcinay055679 commented on frontend/src/app/release-1/shared/dialog/example-dialog/example-dialog.component.ts
> +  selected = '';
is this rly needed?

2023-08-11 10:44 UTC, MarcEgliP commented on frontend/src/app/release-1/shared/dialog/example-dialog/example-dialog.component.spec.ts
> +    await buttons[0].check();
Is not possible, MatRadioButtonHarness has no option to select a radio button by its value.

2023-08-15 14:50 UTC, peggimann approved these changes

2023-08-15 14:53 UTC, merged