Feature/286 improve swagger
puzzle/okr pull request #35
Opened 2022-11-11 13:33 UTC by lkleisa

2022-11-11 14:28 UTC, lkleisa commented
Swagger doc wurde angepasst und überall gleich gemacht. So ist es übersichtlicher. 
Wenn man auf http://localhost:8080/swagger-ui/index.html#/objective-controller/updateObjective ein Objective updaten will, kommt ein Fehler, dass die owner id fehlt. Ich weiss nicht, wieso das so ist, sollte aber nicht an swagger liegen.

2022-11-11 15:03 UTC, tuxmatta requested changes
Habe im SwaggerUI nur den **team-controller** überprüft. Bitte das Review auch auf die anderen Bereiche vom SwaggerUI überprüfen.

2022-11-11 15:03 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/controller/TeamController.java
> +            @ApiResponse(responseCode = "200", description = "Created new Team.",
Ich kann diesen HTTP Code 200 über Swagger nicht erreichen!

2022-11-11 15:20 UTC, lkleisa commented on backend/src/main/java/ch/puzzle/okr/controller/KeyResultController.java
> -    public List<KeyResultDto> getAllKeyResults() {
Diese ist nicht in den Anforderungen dokumentiert und wurde schon einmal von Niklas entfernt, wurde dann aber wieder hinzugefügt.

2022-11-11 15:23 UTC, lkleisa commented on backend/src/main/java/ch/puzzle/okr/controller/TeamController.java
> +            @ApiResponse(responseCode = "200", description = "Created new Team.",
Du hast wohl auf einer älteren Version geschaut, bei mir geht es. Kannst du nochmals aktualisieren und probieren?

2022-11-12 08:28 UTC, tuxmatta approved these changes

2022-11-12 08:29 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/controller/KeyResultController.java
> -    public List<KeyResultDto> getAllKeyResults() {
ok

2022-11-12 08:29 UTC, merged