Feature/300 display keyresults on objective
puzzle/okr pull request #368
Opened 2023-09-04 09:54 UTC by RandomTannenbaum

- **Attention**: Branch was created from feature/303-create-overview
- Add keyresult component
- Load data that it gets from objective component with @Input()
- Include keyresult in objective component, so its displayed correctly
- No tests needed

2023-09-04 11:08 UTC, tuxmatta requested changes

2023-09-04 11:08 UTC, tuxmatta commented on frontend/src/app/keyresult/keyresult.component.html
> +  <p *ngIf="keyResult.lastCheckIn.createdOn != undefined; else noCheckin" class="last-checkin">
div verwenden

2023-09-04 11:08 UTC, tuxmatta commented on frontend/src/app/keyresult/keyresult.component.html
> +  <ng-template #noCheckin class="last-checkin">Noch kein Check-In vorhanden</ng-template>
Auch mit einem div

2023-09-04 11:08 UTC, tuxmatta commented on frontend/src/app/keyresult/keyresult.component.ts
> +  ngOnInit(): void {}
ngOnInit() löschen

2023-09-07 13:02 UTC, peggimann requested changes

2023-09-07 13:02 UTC, peggimann commented on frontend/src/styles.scss
> +  font-size: 0.7em;
use rem

2023-09-07 13:13 UTC, merged