Feature/332 confidence component
puzzle/okr pull request #381
Opened 2023-09-07 07:17 UTC by kcinay055679

2023-09-13 06:51 UTC, tuxmatta requested changes

2023-09-13 06:51 UTC, tuxmatta commented on frontend/angular.json
> +            "assets": ["./src/favicon.ico", "./src/assets"],
Richtig wäre `"assets": ["src/favicon.ico", "src/assets"],`
https://angular.io/guide/workspace-config#asset-config

2023-09-13 06:51 UTC, tuxmatta commented on frontend/angular.json
> +              "./src/style/styles.scss"
Ebenso bei den styles: `src/` oder `node/`

2023-09-13 06:51 UTC, tuxmatta commented on frontend/src/app/app.module.ts
> +import { FormsModule, ReactiveFormsModule } from '@angular/forms';
Braucht der `MatSliderModule` das `FormsModule`?

2023-09-13 06:51 UTC, tuxmatta commented on frontend/src/style/styles.scss
> +.keyResult-attribute-show {
Kann man den Hinweis einfügen, dass es sich um das Confidence handelt? Vielleicht `.confidence-attribute-...`

2023-09-13 06:51 UTC, tuxmatta commented on frontend/src/app/confidence/confidence.component.html
> +    (input)="keyResult.lastCheckIn!.confidence = $event.value!"
von wo kommt das `$event`? Aus der `mat-slider`?

2023-09-15 13:16 UTC, kcinay055679 commented on frontend/src/app/app.module.ts
> +import { FormsModule, ReactiveFormsModule } from '@angular/forms';
Nein nicht direkt, aber ngModel wird nur vom FormsModule bereitgestellt

2023-09-15 13:16 UTC, kcinay055679 commented on frontend/src/app/confidence/confidence.component.html
> +    (input)="keyResult.lastCheckIn!.confidence = $event.value!"
ja, dies wird von (input) emittet

2023-09-15 13:17 UTC, kcinay055679 commented on frontend/src/style/styles.scss
> +.keyResult-attribute-show {
ich denke das man diese Klasse auch noch für andere Attribute auf dem KeyResult verwerden könnte

2023-09-18 11:37 UTC, tuxmatta approved these changes

2023-09-18 11:37 UTC, merged