Feature/305 create and edit keyresult
puzzle/okr pull request #383
Opened 2023-09-08 06:03 UTC by RandomTannenbaum

- Create KeyResultDialog component
- Open this component as dialog, when clicking on "Key result hinzufügen" button on objective
- Add necessary buttons and input fields to KeyResultDialog component

2023-10-02 08:19 UTC, RandomTannenbaum commented
Adjust button styling according to [branch 304](https://github.com/puzzle/okr/tree/feature/304-objective-dialog)

2023-10-02 15:46 UTC, tuxmatta requested changes

2023-10-02 15:46 UTC, tuxmatta commented on frontend/src/app/shared/services/notifier.service.ts
> +  keyResultsChanges: Subject<{ keyResult: KeyResult; changeId: number | null; objective: Objective; delete: boolean }> =
Das gefällt mir nicht so ganz.

2023-10-02 15:46 UTC, tuxmatta commented on frontend/src/style/custom_angular.scss
> +@import "custom_angular.components";
Imports an den Anfang verschieben.

2023-10-03 06:07 UTC, tuxmatta approved these changes

2023-10-03 06:07 UTC, tuxmatta commented on frontend/src/app/shared/services/notifier.service.ts
> +  keyResultsChanges: Subject<{ keyResult: KeyResult; changeId: number | null; objective: Objective; delete: boolean }> =
Dieses Problem lagern wir in eine eigene Story aus.

2023-10-03 09:22 UTC, merged