Create angular app for frontend
puzzle/okr pull request #39
Opened 2022-11-16 07:03 UTC by lkleisa

2022-11-16 07:57 UTC, tuxmatta requested changes
Da Verzeichnis `.vscode` löschen und dann ist ok.

2022-11-16 07:57 UTC, tuxmatta commented on frontend/.vscode/extensions.json
> +{
Wieso .vscode Dateien?

2022-11-16 07:58 UTC, lkleisa commented on frontend/.vscode/extensions.json
> +{
Waren bei deinem Angular Demo Projekt dabei, da dachte ich, es braucht sie. Soll ich sie löschen?

2022-11-17 07:37 UTC, tuxmatta approved these changes

2022-11-17 07:37 UTC, merged