Feature/396 upgrade angular
puzzle/okr pull request #403
Opened 2023-09-12 07:51 UTC by kcinay055679

2023-09-15 09:34 UTC, kcinay055679 commented
Upgrade done.
example dialog tests fail because of an error related to [proxy zone](https://github.com/thymikee/jest-preset-angular/issues/2162)

2023-09-18 10:55 UTC, tuxmatta requested changes

2023-09-18 10:55 UTC, tuxmatta commented on frontend/src/app/shared/dialog/example-dialog/error-messages.json
> +{
remove this file

2023-09-18 10:55 UTC, tuxmatta commented on frontend/src/app/shared/dialog/example-dialog/example-dialog.component.spec.ts
> +              advance(100);
remove `100`

2023-09-18 10:55 UTC, tuxmatta commented on frontend/tsconfig.json
> +    "target": "ES2022",
change to `es2022`

2023-09-18 11:19 UTC, tuxmatta approved these changes

2023-09-18 11:19 UTC, merged