Feature/301 filter dashboard
puzzle/okr pull request #42
Opened 2022-11-18 10:51 UTC by lkleisa

2022-11-22 14:35 UTC, tuxmatta commented on frontend/src/app/dashboard/dashboard.component.spec.ts
> +  it('should display 5 items in cycle dropdown', () => {
should display 6 statt 5

2022-11-22 14:38 UTC, tuxmatta commented on frontend/src/app/dashboard/team.service.ts
> +  public getQuarter(date = new Date()) {
Das ist mit Abstand die grösste und komplizierteste  Codeblock der du in dieser Story geschrieben hat. Wieso testest du diese nicht ausführlich?
Zum Beispiel mit verschiedenen Tagen: erster Tag im Jahr, letzter Tag im Jahr ...
Dieser Test ist hat fast keine Abhängigkeiten zu Jest oder Karma. Der kannst du gut umsetzten.

2022-11-23 06:45 UTC, lkleisa commented on frontend/src/app/dashboard/dashboard.component.html
> +          [value]="team"
Diese Möglichkeit ist mir nicht in den Sinn gekommen. Mat-form-field kann es auch nur mit der id

2022-11-23 09:06 UTC, tuxmatta requested changes
Noch zwei Kleinigkeiten, dann hast du es geschafft.

2022-11-23 09:06 UTC, tuxmatta commented on frontend/src/app/dashboard/dashboard.component.html
> +          [value]="team.name"
Ich würde hier die ID übergeben, da wir anschliessend der orangen Komponenten die ID übergeben müssen. Schlage vor, dass wir das mit dem Puzzle Team zuoberst fallen lassen. Das muss später sowieso das Backend machen.

2022-11-23 09:06 UTC, tuxmatta commented on frontend/src/app/dashboard/dashboard.component.html
> +      <mat-label>Zyklus</mat-label>
Verwende statt Zyklus direkt Quarter. Im Label und auch in allen Variablen sowie Funktionen. Figma stimmt hier nicht. Das Domain-Modell ist korrekt.

2022-11-23 09:43 UTC, tuxmatta approved these changes

2022-11-23 09:44 UTC, merged