Feature/304 objective dialog
puzzle/okr pull request #421
Opened 2023-09-25 12:48 UTC by lkleisa

2023-09-29 09:01 UTC, MarcEgliP requested changes

2023-09-29 09:01 UTC, kcinay055679 commented on frontend/src/app/app.component.html
> +        *ngIf="sidenavContentInformation != undefined && drawerOpen"
done

2023-10-06 13:22 UTC, MarcEgliP approved these changes

2023-10-06 14:58 UTC, peggimann requested changes
include tests for services

2023-10-06 14:58 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/repository/CheckInRepository.java
> +
is not nescessary

2023-10-06 14:58 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/service/validation/ObjectiveValidationService.java
> +        if (checkInBusinessService.getCheckInAmountByObjectiveId(id) != 0) {
this error should not be thrown, a delete on an objective should delete its corresponding key results and the corresponding check ins

2023-10-06 14:58 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/business/CheckInBusinessServiceTest.java
> +        checkInBusinessService.getCheckInAmountByObjectiveId(1L);
this test can be removed

2023-10-06 14:58 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/validation/ObjectiveValidationServiceTest.java
> +        ResponseStatusException exception = assertThrows(ResponseStatusException.class,
this test is not needed

2023-10-06 14:58 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/validation/ObjectiveValidationServiceTest.java
> +    CheckInBusinessService checkInBusinessService = Mockito.mock(CheckInBusinessService.class);
this mock is not needed

2023-10-06 14:58 UTC, peggimann commented on frontend/src/app/app.component.ts
> +    document.getElementById('bannerComponent')!.classList.add('backdrop');
should not bee needed anymore.

2023-10-06 15:07 UTC, MarcEgliP commented on backend/src/main/java/ch/puzzle/okr/repository/CheckInRepository.java
> +
Still needed

2023-10-06 15:56 UTC, peggimann approved these changes

2023-10-06 15:57 UTC, merged