Feature/306 check in erfassen und bearbeiten
puzzle/okr pull request #427
Opened 2023-09-26 14:15 UTC by MarcEgliP

Was gemacht wurde:

- Dialog zur Erstellung eines Check-ins implementiert

2023-10-03 08:51 UTC, tuxmatta requested changes

2023-10-03 08:51 UTC, tuxmatta commented on frontend/src/app/shared/custom/custom-input/custom-input.component.spec.ts
> +});
Testen, ob die beiden Imput-Variablen im Template auch gesetzt werden.

2023-10-03 08:51 UTC, tuxmatta commented on frontend/src/app/shared/pipes/unit-transformation/unit-transformation.pipe.ts
> +export class UnitTransformationPipe implements PipeTransform {
Könnte  man die Namen der beiden Pipes so gestalten, dass der Zweck eindeutiger ist?

2023-10-03 14:14 UTC, MarcEgliP commented on frontend/src/app/shared/custom/custom-input/custom-input.component.spec.ts
> +});
ergänzt

2023-10-04 09:22 UTC, tuxmatta requested changes

2023-10-04 09:22 UTC, tuxmatta commented on frontend/src/app/shared/pipes/unit-value-transformation/unit-transformation.pipe.spec.ts
> +import { UnitValueTransformationPipe } from './unit-value-transformation.pipe';
1. Der Dateiname des Tests passt nicht.
2. Die Pipe ist nicht getestet. Eine Pipe lässt sich sehr einfach testen.

**Allgemein**
- Ist es nicht notwendig, bei beiden Pipes der Wert (Zahl) und die Einheit in der Pipe zu verarbeiten:
   - `10'000 CHF` oder `10'000` oder `10 000 CHF` oder `10000` -> parse -> `10000` + `Type Unit.CHF`
   - `10000` + `Type Unit.CHF` -> format ->  `10'000 CHF`
- Könntest du nicht die Pipes zum Beispiel nicht so benennen:
   - parse-number-and-unit.pipe.ts  (Parse den eingegebener Wert)
   - format-number-and-unit.pipe.ts (Formatiere den Wert für eine schöne Ausgabe)

_Wir müssen dies miteinander nach dem Mittag besprechen._

2023-10-04 09:22 UTC, tuxmatta commented on frontend/src/app/shared/pipes/unit-label-transformation/unit-label-transformation.pipe.spec.ts
> +});
Die Pipe ist nicht getestet. Eine Pipe lässt sich sehr einfach testen. Schau zuerst den Kommentar zur zweiten Pipe an.

2023-10-04 10:42 UTC, MarcEgliP commented on frontend/src/app/shared/dialog/checkin/check-in-form-metric/check-in-form-metric.component.ts
> +    return +this.dialogForm?.controls['value'].value?.replaceAll('%', '').replaceAll('.-', '')!;
Nein

2023-10-04 13:37 UTC, tuxmatta approved these changes

2023-10-04 13:38 UTC, merged