Feature/refactor frontend
puzzle/okr pull request #449
Opened 2023-10-10 06:08 UTC by MarcEgliP

2023-10-13 12:11 UTC, kcinay055679 requested changes

2023-10-13 12:11 UTC, kcinay055679 commented on frontend/src/app/shared/custom/sidepanel/sidepanel.component.html
> +<div #container class="container-fluid">
move down backdrop by 48 px

2023-10-13 14:22 UTC, kcinay055679 submitted a review, later dismissed

2023-10-16 07:00 UTC, peggimann requested changes

2023-10-16 07:00 UTC, peggimann commented on frontend/src/app/team/team.component.ts
> +  private _overviewEntity = new BehaviorSubject<OverviewEntity>({} as OverviewEntity);
reaneme to overviewEntity$

2023-10-16 15:38 UTC, peggimann approved these changes

2023-10-16 15:38 UTC, peggimann commented on frontend/src/app/objective/objective.component.ts
> +  private _objective = new BehaviorSubject<ObjectiveMin>({} as ObjectiveMin);
rename to objective$

2023-10-16 15:40 UTC, merged