Feature/319: Action plan
puzzle/okr pull request #498
Opened 2023-10-23 14:49 UTC by lkleisa

2023-11-02 12:44 UTC, peggimann requested changes
implement list on key result detail

2023-11-02 12:44 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/service/business/ActionBusinessService.java
> +        return actionPersistenceService.getActionsByKeyResultIdOrderByPriorityAsc(keyResultId);
missing validate on get

2023-11-02 12:44 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/service/persistence/ActionPersistenceService.java
> +        return ((ActionRepository) this.repository).getActionsByKeyResultIdOrderByPriorityAsc(keyResultId);
use getRepository() instead of typecast

2023-11-02 12:44 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/service/validation/ActionValidationService.java
> +    }
maybe implement method validate on get by key result id, use keyResultValidation service to verify existence of key result

2023-11-02 12:44 UTC, peggimann commented on backend/src/main/resources/db/migration/V2_0_8__createActionTable.sql
> +create table if not exists action
restart sequence at 500

2023-11-02 12:44 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/controller/KeyResultControllerIT.java
>      @MockBean
@Mock instead of @MockBean

2023-11-02 16:07 UTC, lkleisa commented
Fix bug with version when checking action and edit then keyresult

2023-11-03 08:00 UTC, peggimann requested changes

2023-11-03 08:30 UTC, peggimann approved these changes

2023-11-03 08:31 UTC, merged