Bug/503 fix number of overview calls
puzzle/okr pull request #528
Opened 2023-10-31 16:04 UTC by RandomTannenbaum

2023-11-03 07:13 UTC, RandomTannenbaum commented on frontend/src/app/team-filter/team-filter.component.ts
> +  ) {}
check if needs to be reverted

2023-11-07 14:00 UTC, MarcEgliP approved these changes

2023-11-07 15:34 UTC, tuxmatta requested changes

2023-11-07 15:34 UTC, tuxmatta commented on frontend/src/app/application-top-bar/application-top-bar.component.ts
> +      username.next(this.oauthService.getIdentityClaims()['name']);
move username subject to this component

2023-11-08 05:38 UTC, tuxmatta approved these changes

2023-11-08 05:40 UTC, merged