312/Preset des Users
puzzle/okr pull request #556
Opened 2023-11-06 13:57 UTC by ManuelMoeri

2023-11-07 15:00 UTC, MarcEgliP submitted a review, later dismissed

2023-11-08 08:04 UTC, tuxmatta requested changes

2023-11-08 09:19 UTC, ManuelMoeri commented
Review vom 08.11.2023 von @tuxmatta:

Kurz zur Info zum zusammenfassen des Tests von Lias und meinem Test. Meine lösung ist im folgenden Screenshot angehängt. Leider kann man das .setValue auf dem keyResultForm nicht einfach entfernen weil seit dem 'KeyResultType' component Validatoren auf dem strechtgoal, unit & baseline sind. Da der KR-type automatisch metric ist werden diese Validatoren eingeschalten. Vorausgesetzt das ich dann das .setValue entferne gibt mir das "keyResultForm.invalid.toBeFalsy" ein "True" zurück und der Test failt. Darum ist es nötig diedas .setValue beizubehalten und werte mit Validatoren zu setzen.

2023-11-08 09:59 UTC, tuxmatta approved these changes

2023-11-08 09:59 UTC, merged