bring back changes from old branch
puzzle/okr pull request #607
Opened 2023-11-24 07:04 UTC by RandomTannenbaum

2023-11-24 16:08 UTC, RandomTannenbaum commented
- Einzeln failen noch 2 specs. Das sind `Tabing` und `Teamverwaltung`. Mit einzeln ist gemeint, wenn man vor jedem run eines spec-files Spring-boot neustartet.
- Wenn diese gefixed sind, müssen alle abhängigkeiten aufgelöst werden, sollten diese denn nach dem fixen aller tests noch vorhanden sein.
- Ausserdem sollte noch überprüft werden, ob die Tests im headless mode auch laufen, denn letztes Mal als ich das gemacht habe, haben mehr Tests gefailed als im normalen mode.

2023-12-01 15:59 UTC, RandomTannenbaum commented
- Momentan failen noch tests bei den tabbing tests, den team tests und den teammanagement tests.
- Wenn diese wieder laufen, müssen noch die Abhängigkeiten beseitigt werden.
- Da die Tests auf der Pipeline headed laufen, müssen sie im headless mode nicht laufen.

2023-12-05 13:50 UTC, tuxmatta requested changes

2023-12-05 13:50 UTC, tuxmatta commented on .run/OkrApplication-Dev.run.xml
> +    <option name="ALTERNATIVE_JRE_PATH" value="$USER_HOME$/.sdkman/candidates/java/current" />
Ist diese Umstellung auf `$USER_HOME$/.sdkman/candidates/java/current` bewusst gemacht worden?

2023-12-05 13:50 UTC, tuxmatta commented on .run/OkrApplication-E2E.run.xml
> +    <option name="ALTERNATIVE_JRE_PATH" value="$USER_HOME$/.sdkman/candidates/java/current" />
Ist diese Umstellung auf `$USER_HOME$/.sdkman/candidates/java/current` bewusst gemacht worden?

2023-12-05 14:19 UTC, tuxmatta approved these changes

2023-12-05 14:19 UTC, merged