Feature/577 focus styling
puzzle/okr pull request #632
Opened 2023-11-28 10:10 UTC by MarcEgliP

2023-12-01 13:53 UTC, MarcEgliP commented on frontend/src/app/action-plan/action-plan.component.spec.ts
> +    expect((component.activeItem = 1));
Das

2023-12-04 07:32 UTC, peggimann requested changes

2023-12-04 07:32 UTC, peggimann commented on frontend/src/app/action-plan/action-plan.component.ts
> +
document why this is needed

2023-12-04 07:36 UTC, MarcEgliP commented on frontend/src/app/action-plan/action-plan.component.ts
> +
comment has been added

2023-12-04 08:05 UTC, merged