Feature/306/321/304
puzzle/okr pull request #66
Opened 2022-12-02 14:33 UTC by lkleisa

2022-12-05 15:56 UTC, tuxmatta requested changes
1. Wieso ist die Komponente TeamDetailComponent in diesem Branch?
2. Bei allen Angular Komponenten muss die folgende ChangeDetection definiert sein: changeDetection: ChangeDetectionStrategy.OnPush
3. Überall: Replace this <b> tag by <strong>.

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.ts
> +  ngOnInit(): void {
wenn kein Gebrauch, ngOnInit löschen

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.ts
> +  keyResultList!: Observable<KeyResultMeasure[]>
Ist gefährlich keyResultList mit ! zu setzen, wenn man so spät die Variable initialisiert. Ich würde  keyResultList mit einem BehaviorSubject initialisieren:
`keyResultList: Observable<KeyResultMeasure[]> = new BehaviorSubject([]);`

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.ts
> +  public addResult() {
Werden diese Methoden aufgerufen?

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.scss
> +
Werden wirklich alle CSS Instruktionen in dieser Datei verwendet?

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.spec.ts
>  import { By } from '@angular/platform-browser';
Imports aufräumen

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/objective/objective-detail/objective-detail.component.ts
> +  ngOnInit(): void {
wenn kein Gebrauch, ngOnInit löschen

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/objective/objective-detail/objective-detail.component.html
> +  <p class="objective-cycle">
überall: `Replace this <b> tag by <strong>`.

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-row/key-result-row.component.scss
> +.measure-date {
Werden wirklich alle CSS Instruktionen in dieser Datei verwendet?

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-detail/key-result-detail.component.html
> +      <p>
Diese beiden Paragraphen sollten nicht angezeigt werden, wenn es keine Measure hat.

2022-12-05 15:56 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-detail/key-result-detail.component.ts
> +  ngOnInit(): void {}
wenn kein Gebrauch, ngOnInit löschen

2022-12-07 09:56 UTC, lkleisa commented
Die TeamDetail Komponente ist in diesem Branch, da wir für eine bessere Ordnung Team, KeyResult und Objective Module erstellt haben. Daher ist TeamDetail jetzt im team module in das ist jetzt halt auch gerade hier in diesem Branch.

2022-12-07 09:57 UTC, lkleisa commented
Momentan sind alle Feedbacks implementiert und ich starte mit dem Schreiben für die Tests. Sonst funktioniert alles

2022-12-07 14:47 UTC, tuxmatta requested changes

2022-12-07 14:47 UTC, tuxmatta commented on frontend/package.json
> +    "@angular/compiler-cli": "^14.2.0 ",
Leerschlag hinter Version entfernen.

2022-12-07 14:47 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-row/key-result-row.component.spec.ts
> +    // @ts-ignore
`// @ts-ignore` ist überflüssig

2022-12-07 14:47 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-row/key-result-row.component.ts
> +    if (formattedDate == null) {
Strict Equals Operator (===) verwenden

2022-12-07 14:47 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.spec.ts
> +  // @ts-ignore
`// @ts-ignore` braucht es nicht

2022-12-07 15:39 UTC, tuxmatta approved these changes

2022-12-07 15:39 UTC, merged