remove notnull constraint from dates on quarter model in backend writ…
puzzle/okr pull request #754
Opened 2024-01-17 12:54 UTC by lkleisa

…e new db migration file to remove not null constraints from db

2024-01-18 08:02 UTC, lkleisa commented on frontend/src/app/shared/dialog/objective-dialog/objective-form.component.html
> +    <div class="d-flex flex-row gap-2">
There were some styling faults, when editing or duplicating an objective, I've fixed them

2024-01-18 15:18 UTC, lkleisa commented on backend/src/main/resources/db/migration/V2_1_2__updateOverviewView.sql
> +DROP VIEW IF EXISTS OVERVIEW;
Is the name of the migration correct?

2024-01-18 15:22 UTC, lkleisa commented on frontend/src/assets/i18n/de.json
> +      "POST_BACKLOG": "Das Objective wurde als Draft im Backlog gespeichert.",
Text approved by Pippo

2024-01-22 09:14 UTC, peggimann requested changes
- Wenn ein Objective im Backlog erstellt wird, sollte nur der Als Draft speichern Button vorhanden sein
- Ein Objective welches sich im Backlog befindet, sollte via 3 Punkte Menü veröffentlicht werden können --> Auswahl nur aus "richtigen Quartern" 
- Ein bereits veröffentlichtes Objective sollte ins Backlog verschoben werden können, dabei wechselt sich der Status zu Draft, abgeschlossene Objectives können nicht in den Backlog verschoben werden
- regex zum überprüfen ob Backlog oder Quartal

2024-01-24 11:18 UTC, peggimann submitted a review, later dismissed

2024-01-24 14:12 UTC, peggimann approved these changes

2024-01-24 14:13 UTC, merged