Feature/731 plussign balance
puzzle/okr pull request #764
Opened 2024-01-22 12:48 UTC by ManuelMoeri

2024-01-23 10:57 UTC, MarcEgliP submitted a review, later dismissed

2024-01-24 08:22 UTC, peggimann requested changes

2024-01-24 08:22 UTC, peggimann commented on frontend/src/style/styles.scss
> +  margin: 0 6px 1px 9px !important;
```
img.add-cross-button  {
  width: 0.65rem;
  margin: 0 6px 1px 9px;
}
```
would be better solution

2024-01-24 11:07 UTC, peggimann approved these changes

2024-01-24 11:07 UTC, merged