Feature/330 measure date
puzzle/okr pull request #77
Opened 2022-12-14 08:38 UTC by kcinay055679

2022-12-16 13:15 UTC, tuxmatta requested changes
Diese Arbeit wurde sehr schlecht umgesetzt!
* Zum Beispiel ist das Backend ist nicht vollständig angepasst: Das MeasureDate wird über die REST-Schnittstelle fast nirgends zurückgegeben!
* Die automatisierten Tests im Frontend wie auch im Backend müssen überprüfen, ob das richtige Datum angezeigt wird.
* Diese Arbeit kann nicht von Hand getestet worden sein (Smoktest). Im Frontend wird immer noch das created_on Datum angezeigt. Das müsste zwingend auffallen.
* Es ist auch interessant, dass man im Frontend ausser am KeyResultService keine Änderungen an einer Komponente oder Template machen muss um das MeasureDate anzuzeigen.


Dies ist alles andere als eine sorgfältig Arbeit.

2022-12-16 13:15 UTC, tuxmatta commented on frontend/src/app/objective/objective-detail/objective-detail.component.spec.ts
> +        measureDate: new Date('2022-12-07T00:00:00'),
Unterschiedliche Datum verwenden.

2022-12-16 13:15 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.spec.ts
> +        measureDate: new Date('2022-12-07T00:00:00'),
Unterschiedliche Datum verwenden.

2022-12-16 13:15 UTC, tuxmatta commented on frontend/src/app/objective/objective-detail/objective-detail.component.spec.ts
> +        measureDate: new Date('2022-12-07T00:00:00'),
Unterschiedliche Datum verwenden.

2022-12-16 13:15 UTC, tuxmatta commented on frontend/src/app/objective/objective-row/objective-row.component.spec.ts
> +        measureDate: new Date('2022-12-07T00:00:00'),
Unterschiedliche Datum verwenden.

2022-12-16 13:15 UTC, tuxmatta commented on frontend/src/app/keyresult/keyresult-form/keyresult-form.component.spec.ts
> +      measureDate: new Date('2022-12-07T00:00:00'),
Unterschiedliche Datum verwenden.

2022-12-16 13:15 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-row/key-result-row.component.spec.ts
> +      measureDate: new Date('2022-12-07T00:00:00'),
Unterschiedliche Datum verwenden.

2022-12-16 13:15 UTC, tuxmatta commented on frontend/src/app/keyresult/key-result-detail/key-result-detail.component.spec.ts
> +      measureDate: new Date('2022-12-07T00:00:00'),
Unterschiedliche Datum verwenden.

2022-12-28 08:34 UTC, peggimann commented on backend/src/test/java/ch/puzzle/okr/service/MeasureServiceTest.java
> +import java.util.Date;
remove unused imports

2022-12-28 08:34 UTC, peggimann commented on frontend/src/app/keyresult/key-result-row/key-result-row.component.ts
> +    if (this.keyResult.measure?.measureDate! == undefined) {
maybe remove exclamation mark

2022-12-28 08:38 UTC, peggimann approved these changes

2022-12-28 08:39 UTC, merged