Feature/279 entitys
puzzle/okr pull request #8
Opened 2022-11-01 08:20 UTC by kcinay055679

[Ticket](https://app.zenhub.com/workspaces/puzzle-bbt-6020f3723c433b000e12ff51/issues/puzzle-bbt/bbt/279)

2022-11-01 13:38 UTC, tuxmatta requested changes

2022-11-01 13:38 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/models/Team.java
> -
Wieso ist der Build wieder gelöscht?

2022-11-01 13:38 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/models/Team.java
> +@Table(name = "team")
Wieso ist @Table Annotation wieder drin?  Bitte entfernen.

2022-11-01 13:38 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/models/User.java
>  @Table(name = "person")
Wieso ist hier die @Table Annotation vornanden? Bitte entfernen.

2022-11-01 13:38 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/models/Team.java
>      private Team(Builder builder) {
Diese Klasse hat Kompilierungsfehler! Bitte sorgfältiger Arbeiten!!

2022-11-03 07:50 UTC, tuxmatta commented on backend/src/main/java/ch/puzzle/okr/models/User.java
>  @Table(name = "person")
Diese Annotation ist doch notwendig: PostgreSQL KeyWord: user

2022-11-03 09:48 UTC, peggimann requested changes

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/KeyResult.java
> +        public KeyResult build() {
should be last method in class

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/Objective.java
> +        return Objects.equals(getTitle(), objective.getTitle()) && Objects.equals(getTeam(), objective.getTeam()) && Objects.equals(getQuarter(), objective.getQuarter());
multiple attributes are missing

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/Objective.java
> +        return Objects.hash(getTitle(), getTeam(), getQuarter());
multiple attributes are missing

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/Quarter.java
> +    public boolean equals(Object o) {
id is missing

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/Quarter.java
> +    public int hashCode() {
id is missing

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/Team.java
> +    @Override
id is missing

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/Team.java
> +    public int hashCode() {
id is missing

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/Team.java
>  package ch.puzzle.okr.models;
order is not equal to other models

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/User.java
> +    public boolean equals(Object o) {
attributes are missing

2022-11-03 09:48 UTC, peggimann commented on backend/src/main/java/ch/puzzle/okr/models/User.java
> +    public int hashCode() {
attributes are missing

2022-11-03 10:17 UTC, peggimann approved these changes

2022-11-03 10:20 UTC, merged