Feature/339 keyresult form test
puzzle/okr pull request #90
Opened 2022-12-16 13:29 UTC by lkleisa

2022-12-19 10:10 UTC, tuxmatta requested changes
Vielleicht bei der `describe('KeyresultFormComponent Create KeyResult',` auch das MatSelectHarness verwenden.

2022-12-19 10:10 UTC, tuxmatta commented on frontend/src/app/keyresult/keyresult-form/keyresult-form.component.spec.ts
> +      // doku https://material.angular.io/guide/using-component-harnesses
Link entfernen

2022-12-21 06:40 UTC, lkleisa commented
Ich habe die vorgeschlagenen Änderungen von Jonas implementiert und beim zweiten DropDown auch die Variante von Niklas mit dem MatSelectHarness eingesetzt.

2022-12-21 08:03 UTC, tuxmatta approved these changes

2022-12-21 08:03 UTC, merged