Bug/949 keycloak error
puzzle/okr pull request #982
Opened 2024-08-09 13:45 UTC by kcinay055679

2024-09-06 13:17 UTC, pizzi-cato requested changes

2024-09-06 13:17 UTC, pizzi-cato commented on backend/src/main/java/ch/puzzle/okr/ForwardFilter.java
>          HttpServletRequest request = (HttpServletRequest) servletRequest;
wozu braucht es dann den Filter überhaupt?

2024-09-09 05:44 UTC, kcinay055679 commented on backend/README.md
> +- if any permission issues occur, following folders
ist angepasst.

2024-09-09 05:44 UTC, kcinay055679 commented on backend/src/main/resources/db/data-migration/V2_0_99__newQuarterData.sql
> +values (8, 'GJ 23/24-Q3', '2024-01-01', '2024-03-31'),
ist angepasst.

2024-09-09 05:45 UTC, kcinay055679 commented on backend/src/main/java/ch/puzzle/okr/ForwardFilter.java
>          HttpServletRequest request = (HttpServletRequest) servletRequest;
Ich habe ihn zwecks logging noch stehen gelassen.

2024-09-09 08:03 UTC, pizzi-cato approved these changes

2024-09-09 08:06 UTC, merged